language: python

python:
  - "3.5"

env:
  matrix:
    include:
      - python: "3.5"
        env: TOX_ENV=py35-dj22
      - pyton: "3.5"
        env: TOX_ENV=py35-cov

install:
  - pip install tox-travis

script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
